name: Build macOS Distribution

# Trigger manually or on release tags
on:
  workflow_dispatch:    # Manual trigger
    inputs:
      version:
        description: 'Version for Release'
        required: false
        default: 'v1.0.0-beta'
  push:
    tags:
      - 'v*.*.*'       # Trigger on tags like v1.0.0, v2.1.3
jobs:
  build-macos:
    runs-on: macos-latest

    permissions:
      contents: write
      discussions: write
    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2️⃣ Set up Java 25
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '25'
          java-package: jdk
      # 3️⃣ Cache Gradle dependencies (optional, speeds up builds)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts','**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4️⃣ Build the macOS distribution using Gradle
      - name: Build distribution
        run: ./gradlew jpackage --no-daemon

      # 5️⃣ Upload the .pkg artifact
      - name: Release Upload
        id: release   # <-- add this
        uses: softprops/action-gh-release@v2
        with:
          body: "Release details refer the commits"
          files: build/jpackage/*
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          prerelease: true

      - name: Print release URL
        run: echo "Release URL-  ${{ steps.release.outputs.url }}"

      - name: Print release ID
        run: echo "Release ID- ${{ steps.release.outputs.id }}"
      
      - name: Print upload URL
        run: echo "Upload URL- ${{ steps.release.outputs.upload_url }}"
      
      - name: Print all assets JSON
        run: echo "Assets- ${{ steps.release.outputs.assets }}"
